---
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex
          args: >
            -pdf -file-line-error -halt-on-error -interaction=nonstopmode
            -outdir=docs
      - uses: JamesIves/github-pages-deploy-action@v4.3.1
        with:
          branch: gh-pages
          folder: docs
